server:
  port: 8888

asynctaskthreadpool:
  core_pool_size: 2
  max_pool_size: 10
  queue_capacity: 1000
  thread_name_prefix: my-task-async-pool-
  rejectedExectionHandler:

scheduled-pool-size: 10

kafka:
  broker_urllist:
  client_id:
  group_id_config:
  topic:
    my-topic1:my-topic1
    my-topic2:my-topic2

logging:
  level:
    ROOT: INFO
#    com.example.sdwan1: ERROR
#    com.zaxxer.hikari.pool.HikariPool: WARN
#    org.springframework.kafka: ERROR
  config: classpath:logback.xml

my-profile:
  name: Guide哥
  email: koushuangbwcx@143.cn

wuhan2020: 2020年初武汉爆发了新型冠状病毒，疫情严重，但是，我相信一切都会过去！武汉加油！中国加油！


library:
  location: 湖北武汉加油中国加油
  books:
    - name: 天才基本法
      description: 二十二岁的林朝夕在父亲确诊阿尔茨海默病这天，得知自己暗恋多年的校园男神裴之即将出国深造的消息——对方考取的学校，恰是父亲当年为她放弃的那所。
    - name: 时间的秩序
      description: 为什么我们记得过去，而非未来？时间“流逝”意味着什么？是我们存在于时间之内，还是时间存在于我们之中？卡洛·罗韦利用诗意的文字，邀请我们思考这一亘古难题——时间的本质。
    - name: 了不起的我
      description: 如何养成一个新习惯？如何让心智变得更成熟？如何拥有高质量的关系？ 如何走出人生的艰难时刻？

